# Generated by Django 5.1.7 on 2025-03-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=100)),
                ("admin_email", models.EmailField(max_length=254, unique=True)),
                ("admin_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(max_length=100)),
                ("c_mobile", models.CharField(max_length=15)),
                ("c_email", models.EmailField(max_length=254, unique=True)),
                ("c_pass", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("s_id", models.AutoField(primary_key=True, serialize=False)),
                ("s_name", models.CharField(max_length=100)),
                ("s_contact", models.CharField(max_length=15)),
                ("s_email", models.EmailField(max_length=254, unique=True)),
                ("s_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.shop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.shop"
                    ),
                ),
            ],
        ),
    ]
