# Generated by Django 5.1.7 on 2025-03-10 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="p_description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="p_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="p_price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="p_stock",
        ),
    ]
