# Generated by Django 5.1.7 on 2025-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_order_total_price_alter_order_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
